package com.github.shham12.nfc_emv_adaptor.iso7816emv

object EMVTags {
    val TAGS = mapOf(
        "6F" to "File Control Information (FCI) Template",
        "84" to "Dedicated File (DF) Name",
        "A5" to "File Control Information (FCI) Proprietary Template",
        "BF0C" to "File Control Information (FCI) Issuer Discretionary Data",
        "61" to "Application Template",
        "4F" to "Application Identifier (AID) – card",
        "50" to "Application Label",
        "87" to "Application Priority Indicator",

        "42" to "Issuer Identification Number (IIN)",
        "57" to "Track 2 Equivalent Data",
        "5A" to "Application Primary Account Number (PAN)",
        "6F" to "File Control Information (FCI) Template",
        "70" to "EMV Proprietary Template",
        "71" to "Issuer Script Template 1",
        "72" to "Issuer Script Template 2",
        "73" to "Directory Discretionary Template",
        "77" to "Response Message Template Format 2",
        "80" to "Response Message Template Format 1",
        "81" to "Amount, Authorised (Binary)",
        "82" to "Application Interchange Profile",
        "83" to "Command Template",
        "86" to "Issuer Script Command",
        "87" to "Application Priority Indicator",
        "88" to "Short File Identifier (SFI)",
        "89" to "Authorisation Code",
        "8A" to "Authorisation Response Code",
        "8C" to "Card Risk Management Data Object List 1 (CDOL1)",
        "8D" to "Card Risk Management Data Object List 2 (CDOL2)",
        "8E" to "Cardholder Verification Method (CVM) List",
        "8F" to "Certification Authority Public Key Index",
        "90" to "Issuer Public Key Certificate",
        "91" to "Issuer Authentication Data",
        "92" to "Issuer Public Key Remainder",
        "93" to "Signed Static Application Data",
        "94" to "Application File Locator (AFL)",
        "95" to "Terminal Verification Results",
        "97" to "Transaction Certificate Data Object List (TDOL)",
        "98" to "Transaction Certificate (TC) Hash Value",
        "99" to "Transaction Personal Identification Number (PIN) Data",
        "9A" to "Transaction Date",
        "9B" to "Transaction Status Information",
        "9C" to "Transaction Type",
        "9D" to "Directory Definition File (DDF) Name",
        "A5" to "File Control Information (FCI) Proprietary Template",
        "E0" to "Receive Data Elements",
        "E1" to "Issue Data Elements (Secure)",
        "E2" to "Decision",
        "E3" to "Issue Data Elements (Non-Secure)",
        "C2" to "Encrypted Data",
        "5F20" to "Cardholder Name",
        "5F24" to "Application Expiration Date",
        "5F25" to "Application Effective Date",
        "5F28" to "Issuer Country Code",
        "5F2A" to "Transaction Currency Code",
        "5F2D" to "Language Preference",
        "5F30" to "Service Code",
        "5F34" to "Application Primary Account Number (PAN) Sequence Number",
        "5F36" to "Transaction Currency Exponent",
        "5F50" to "Issuer URL",
        "5F53" to "International Bank Account Number (IBAN)",
        "5F54" to "Bank Identifier Code (BIC)",
        "5F55" to "Issuer Country Code (alpha2 format)",
        "5F56" to "Issuer Country Code (alpha3format)",
        "5F57" to "Account Type",
        "9F01" to "Acquirer Identifier",
        "9F02" to "Amount, Authorised (Numeric)",
        "9F03" to "Amount, Other (Numeric)",
        "9F04" to "Amount, Other (Binary)",
        "9F05" to "Application Discretionary Data",
        "9F06" to "Application Identifier (AID) – terminal",
        "9F07" to "Application Usage Control",
        "9F08" to "Application Version Number",
        "9F09" to "Application Version Number",
        "9F0A" to "Application Selection Registered Proprietary Data",
        "9F0B" to "Cardholder Name Extended",
        "9F0D" to "Issuer Action Code – Default",
        "9F0E" to "Issuer Action Code – Denial",
        "9F0F" to "Issuer Action Code – Online",
        "9F10" to "Issuer Application Data",
        "9F11" to "Issuer Code Table Index",
        "9F12" to "Application Preferred Name",
        "9F13" to "Last Online Application Transaction Counter (ATC) Register",
        "9F14" to "Lower Consecutive Offline Limit",
        "9F15" to "Merchant Category Code",
        "9F16" to "Merchant Identifier",
        "9F17" to "Personal Identification Number (PIN) Try Counter",
        "9F18" to "Issuer Script Identifier",
        "9F1A" to "Terminal Country Code",
        "9F1B" to "Terminal Floor Limit",
        "9F1C" to "Terminal Identification",
        "9F1D" to "Terminal Risk Management Data",
        "9F1E" to "Interface Device (IFD) Serial Number",
        "9F1F" to "Track 1 Discretionary Data",
        "9F20" to "Track 2 Discretionary Data",
        "9F21" to "Transaction Time",
        "9F22" to "Certification Authority Public Key Index",
        "9F23" to "Upper Consecutive Offline Limit",
        "9F26" to "Application Cryptogram",
        "9F27" to "Cryptogram Information Data",
        "9F2D" to "Integrated Circuit Card (ICC) PIN Encipherment Public Key Certificate",
        "9F2E" to "Integrated Circuit Card (ICC) PIN Encipherment Public Key Exponent",
        "9F2F" to "Integrated Circuit Card (ICC) PIN Encipherment Public Key Remainder",
        "9F32" to "Issuer Public Key Exponent",
        "9F33" to "Terminal Capabilities",
        "9F34" to "Cardholder Verification Method (CVM) Results",
        "9F35" to "Terminal Type",
        "9F36" to "Application Transaction Counter (ATC)",
        "9F37" to "Unpredictable Number",
        "9F38" to "Processing Options Data Object List (PDOL)",
        "9F39" to "Point-of-Service (POS) Entry Mode",
        "9F3A" to "Amount, Reference Currency",
        "9F3B" to "Application Reference Currency",
        "9F3C" to "Transaction Reference Currency Code",
        "9F3D" to "TransactionReference Currency Exponent",
        "9F40" to "Additional Terminal Capabilities",
        "9F41" to "Transaction SequenceCounter",
        "9F42" to "Application Currency Code",
        "9F43" to "Application Reference Currency Exponent",
        "9F44" to "Application Currency Exponent",
        "9F45" to "Data Authentication Code",
        "9F46" to "Integrated Circuit Card (ICC) Public Key Certificate",
        "9F47" to "Integrated Circuit Card (ICC) Public Key Exponent",
        "9F48" to "Integrated Circuit Card (ICC) Public Key Remainder",
        "9F49" to "Dynamic Data Authentication Data Object List(DDOL)",
        "9F4A" to "Static Data Authentication Tag List",
        "9F4B" to "Signed Dynamic Application Data",
        "9F4C" to "ICC Dynamic Number",
        "9F4D" to "Log Entry",
        "9F4E" to "Merchant Name and Location",
        "9F4F" to "Log Format",
        "9F53" to "Transaction Category Code ",
        "9F5B" to "Issuer Script Results",
        "9F66" to "Terminal Transaction Qualifier",
        "9F6B" to "Track 2 Data",
        "9F6E" to "Form Factor Indicator",
        "9F7C" to "Customer Exclusive Data",
        "BF0C" to "File Control Information (FCI) Issuer Discretionary Data",
        "DF01" to "Digits",
        "DF02" to "Status Bytes",
        "DF11" to "Acquirer ID",
        "DF12" to "Answer To Reset (ATR)",
        "DF13" to "ISO 7811 Track 1 card data",
        "DF14" to "ISO 7811 Track 2 card data",
        "DF15" to "ISO 7811 Track 3 card data",
        "DF16" to "Enciphered PIN Block",
        "DF17" to "Key Serial Number",
        "DF18" to "Risk Management",
        "DF78" to "Device Serial Number",
        "DF79" to "Kernel Version Number"
    )
}